### ISSUE TITLE
Implement a first game draft

### ISSUE THREAD

**Issue by donscho** [lua-games-2d/breakout#3]
Let's make a first draft of the breakout game. It does not need to be awesome and it does not need awesome feature. The principal goal is: **keep it simple and make it work**. From this starting point, we can then improve and make it fun to play.

**Basic requirements**
* there is only one level and one ball
* each block has one life, i.e., it will be destroyed immediately when it gets hit by the ball
* the player starts with three lifes and loses one each time the ball leaves to bottom screen
* upon level starts and lost balls, the player starts with the ball attached to the paddle, which can be released upon a specific key press

**Not needed**
* animations
* good graphics
* music and sounds

**Milestones**
* [ ] Create an empty window
* [ ] Add the player paddle
* [ ] Make the player paddle move left/right on specific key presses
* [ ] Add the walls and make the player collide using the LÖVE physics module
* [ ] Add the ball and make it collide with the walls and the player
* [ ] Make the ball stick to the player paddle and release it upon specific key press
* [ ] Give the player three lifes and lose one each time the ball leaves the bottom screen
* [ ] Add the blocks and implement collission logic with the ball (remove block when it gets hit by the ball)
